### ISSUE TITLE
Add new Tab to navbar

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#102]

**Comment by YohanKulasinghe** [comment]
- Remove student’s work menu bar from the Project tab and add a new tab to the navigation bar,
- Name it as “Student’s work”

![Picture1](https://user-images.githubusercontent.com/28680211/81533743-59d02200-9384-11ea-93e4-a40ac645c45d.png)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By :  _Chamindika Laksarani_

**Comment by JayaShakthi97** [comment]
May I?

**Comment by YohanKulasinghe** [comment]
Yep, Sure 👍
