### ISSUE TITLE
Add sub menu item for navbar

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#103]

**Comment by YohanKulasinghe** [comment]
- The new “Student’s work” tab has a menu bar that has 4 sub-menus. #102 
    Sub-menus as,
           - First year projects
           - Second year projects
          - Fourth year projects
           - Research publications

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Chamindika Laksarani_

**Comment by PulsaraSandeepa** [comment]
May I do this.

**Comment by YohanKulasinghe** [comment]
Sure  👍
