### ISSUE TITLE
Latest programs section in Home page - Change 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#107]
- Use the squares to add the details of the latest news on the web site as follows. And also those boxes should be clickable to move on the pages which includes the details of news updated or latest programs in event page

![Picture1](https://user-images.githubusercontent.com/28680211/81770575-5365b580-94fe-11ea-9b5b-08704e75f3c6.png)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Chathurya Heshani_ and _Sachithra Rathnayake_

**Comment by Thisuru** [comment]
May I try this?

**Comment by YohanKulasinghe** [comment]
Yea Sure, Please Proceed.
