### ISSUE TITLE
Join community button in Contributors page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#108]

**Comment by YohanKulasinghe** [comment]
You can navigate this page by clicking "Open Source Contributors"  link in the footer section.
- "Join community" button should be placed to the center. and change style as appropriate .

![Picture1](https://user-images.githubusercontent.com/28680211/81771039-97a58580-94ff-11ea-8af9-ac7d79bf9517.png)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Sachithra Rathnayake_

**Comment by I3han** [comment]
Can I?

**Comment by YohanKulasinghe** [comment]
Of Cause, Please Proceed
