### ISSUE TITLE
Add INTECS Logo to admin login page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#110]

**Comment by YohanKulasinghe** [comment]
- Navigate https://intecs-dev.web.app/login
- Add INTECS logo in top of login container (center aligned)
- png logo is already in assert folder 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Sachithra Rathnayake_

**Comment by SahanAmarsha** [comment]
May I implement this? The login page I first implemented is missing now, I can re-add that page also.

**Comment by YohanKulasinghe** [comment]
Sure, You can. I also noted that. ok continue both, thank you.
