### ISSUE TITLE
Remove the messenger chat from dashboard routes

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#111]

**Comment by YohanKulasinghe** [comment]
- no need to display messenger chat in admin routes 
check 
https://intecs-dev.web.app/login
https://intecs-dev.web.app/dashboard

- Remove messenger chat in all admin panel routes 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Chamindika Laksarani_

**Comment by SahanAmarsha** [comment]
I can work on this.

**Comment by YohanKulasinghe** [comment]
OK, Please Continue
