### ISSUE TITLE
Change the contributors page navbar.

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#112]

**Comment by YohanKulasinghe** [comment]
- Navigate https://intecs-dev.web.app/contributes
- Need to remove navbar buttons ( Home, Events, project, gallery about us) 
- Instead of those tabs keep the "Back" button in the nav bar to go back home page of INTECS site

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Sachithra Rathnayake_

**Comment by Tashimadilrukshi** [comment]
May I do this?

**Comment by YohanKulasinghe** [comment]
Sure, You can proceed
