### ISSUE TITLE
Change styles -  Dashboard side navbar

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#120]

**Comment by YohanKulasinghe** [comment]
- Navigate Dashboard https://intecs-dev.web.app/dashboard/
- Observe the colors of the top navbar 
- make changes on the side nav bar to match with top navbar 
- Add relevant Icons in front of nav links

![81466721-66704100-91f1-11ea-9d8e-4092a4a6fdcb](https://user-images.githubusercontent.com/28680211/82007083-f77a6880-9686-11ea-9951-5d42ab3994e3.png)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by Sachin-Mamoru** [comment]
May I try this?

**Comment by YohanKulasinghe** [comment]
Sure, Please Proceed
