### ISSUE TITLE
Change nav link location

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#125]
- Student work sub nav link should remove from the project tab.
- All the sub-items under the "Student work" tab should move to the new "student work tab.

![Picture1](https://user-images.githubusercontent.com/28680211/82232291-12c9ca00-994c-11ea-8062-9393d4727268.png)
 
Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by PulsaraSandeepa** [comment]
May I ?

**Comment by YohanKulasinghe** [comment]
Sure,👍
