### ISSUE TITLE
Change the contributors page section titles

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#126]

**Comment by YohanKulasinghe** [comment]
- Navigate to contributors page https://intecs-dev.web.app/contributes
- Change section titles's styles 
![Picture2](https://user-images.githubusercontent.com/28680211/82233045-05f9a600-994d-11ea-8cad-b94463581c30.jpg)

- Please use appropriate colors 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : _Sachithra Rathnayake_

**Comment by SahanAmarsha** [comment]
I can work on this Ayiye

**Comment by YohanKulasinghe** [comment]
Ok malli, Please proceed
