### ISSUE TITLE
Responsive issue in Contributors page 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#127]

**Comment by YohanKulasinghe** [comment]
- Some cards in the contributors page change their size inappropriately when resizing.
- This is due to an automatic line break happen when div size reduced.
- By Changing the styles, to avoid line break, when resize will fix this issue 

![Picture1](https://user-images.githubusercontent.com/28680211/82233882-44439500-994e-11ea-8008-053bbbb97725.png)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

Reported By : Sachithra Rathnayake

**Comment by JayaShakthi97** [comment]
I can try this

**Comment by YohanKulasinghe** [comment]
OK, Please Proceed
