### ISSUE TITLE
Change Tab Name

### ISSUE THREAD

**Issue by buddhikac96** [INTECS-ITFAC/intecs_webapp_front-end#132]
**Projects** -> **Student's** **Works** -> **Fourth Year Project** 

Change **fourth year projects** into **Final year projects.**

![image](https://user-images.githubusercontent.com/28675970/82763402-0ac6ca00-9e25-11ea-8b76-c623130226da.png)

**Comment by JayaShakthi97** [comment]
Let me do this.

**Comment by buddhikac96** [comment]
Sure. Proceed
