### ISSUE TITLE
Implementing “First year project” Page Header Section

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#144]
- Create a new page under the "First Year projects" tab.
- Display slide show top of the page. ( a carousal like home page).
- Display the name “First Year Project” in front of the slide show. (for now)

Slide show should display 1st-year project stuff, evaluating, Hardware lab pictures, basement lab pictures. (For now, use similar pictures from internet)

Contact INTECS Open Source community for more information. 
(You can find a link to join the community in Read me file.)

Reported by : _Chamindika Laksarani_

**Comment by JayaShakthi97** [comment]
I'd like to try.

**Comment by YohanKulasinghe** [comment]
Sure, Please Proceed.
