### ISSUE TITLE
Implementing “Second year project” Page Header Section

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#146]
- Create a new page under the "Second Year projects" tab.
- Display slide show top of the page. ( a carousal like home page).
- Display the name “Second Year Project” in front of the slide show. (for now)

Contact INTECS Open Source community for more information.
(You can find a link to join the community in Read me file.)

Reported by : _Chamindika Laksarani_

**Comment by NimperX** [comment]
May i work in this issue?

**Comment by YohanKulasinghe** [comment]
Sure, Please proceed.
