### ISSUE TITLE
Page top navigation UI implementation 

### ISSUE THREAD

**Issue by ChanakaUOMIT** [INTECS-ITFAC/intecs_webapp_front-end#27]

**Comment by YohanKulasinghe** [comment]
Navigation UI should contains menus as fallow,

_Home
Events
Project
...LinkIT
...INTECS OpenSource
...Student's Work
Gallery_ 

- Redirect all links to home page (For now using "#")
- Height / Font Size can adjust as you want.
- Overall appearance should match with this. [Image_1](https://drive.google.com/file/d/1Ql5r5iEn6nE09FNzFRWesE4x5x2Yov1t/view?usp=sharing)
- You can find resources [Here](https://drive.google.com/drive/folders/1mS92hlchalRw_xK12n13Dm7Vc9zeROnk?usp=sharing)

Contact INTECS Open Source community for more information. (You can find a link to join community in Read me file.)
