### ISSUE TITLE
Home page carousal implementation

### ISSUE THREAD

**Issue by ChanakaUOMIT** [INTECS-ITFAC/intecs_webapp_front-end#28]

**Comment by YohanKulasinghe** [comment]
Carousal should positioned like this [Image](https://drive.google.com/file/d/1Qi3yEg5dordUrJzzwu_EQrpLL7n4z9-j/view?usp=sharing)
Following folder you can find images for carousal [Here](https://drive.google.com/drive/folders/12vdWd295uAuVt3YTjLx7eEkm5fDRmK9U?usp=sharing)

**Comment by SadheeraMahanama** [comment]
I would like to do the carousel part in this project.

**Comment by YohanKulasinghe** [comment]
OK, Please Proceed
