### ISSUE TITLE
Home page latest program UI component implementation 

### ISSUE THREAD

**Issue by ChanakaUOMIT** [INTECS-ITFAC/intecs_webapp_front-end#29]

**Comment by YohanKulasinghe** [comment]
Latest Program section have two tabs 
1. Competition 
2. Others
Here, shows posts which have published on "events tab".  There should be multiple duplicate component in the section and each carries content from "events tab" But for now latest programs component should creates as follows 

- Appearance of section looks like  [this](https://drive.google.com/file/d/1jQ-rwBM4z-navt1ZafRYzqKc-4bXvlc-/view?usp=sharing)
- Component should have ability to get content from event page.
- Appearance of component should be like [this](https://drive.google.com/file/d/1ZfYfMluc5LPyo7-8shHy38hpN7oPNCY4/view?usp=sharing)
- For initial stage, content of the component left hard corded. 
- You can Find content text and logos [Here](https://drive.google.com/drive/folders/1EQE6V-JRCLWqqN7mhdX8nZ8jO8wBnof5?usp=sharing)

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by Tashimadilrukshi** [comment]
I would like to try this. May I?

**Comment by ChanakaUOMIT** [comment]
OK, Please Proceed
