### ISSUE TITLE
Home page Event list UI component implementation 

### ISSUE THREAD

**Issue by ChanakaUOMIT** [INTECS-ITFAC/intecs_webapp_front-end#30]

**Comment by YohanKulasinghe** [comment]
Event Time Line Section appearance should look like [this](https://drive.google.com/file/d/1K8iKlmHY-eaYbq-thlbk01M2dsEV5XaG/view?usp=sharing)
You can find important resources and **content text** [here](https://drive.google.com/drive/folders/1_JTYEDm38QCwkQz3q2VlhAsNzElh4zKs?usp=sharing)

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by Tharuja** [comment]
I would like to do this part
