### ISSUE TITLE
Home page news feed component implementation

### ISSUE THREAD

**Issue by ChanakaUOMIT** [INTECS-ITFAC/intecs_webapp_front-end#31]
create the basic structure of contact us UI component according to the [(image)](https://drive.google.com/file/d/1ZbrLFewHWCuRGztyc8giWf0mkRLRGNDQ/view?usp=sharing)

**Comment by YohanKulasinghe** [comment]
News feed is text line which shows the latest program and events happened in faculty. for now this lines hard corded. and appearance should look like [this](https://drive.google.com/file/d/1CdtaHftWwKC8d8oaRui98iRthdPiDJqO/view?usp=sharing) 

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by ChandeepaPath** [comment]
I like to try this news feed component.

**Comment by YohanKulasinghe** [comment]
OK, Please Proceed

**Comment by YohanKulasinghe** [comment]
**This issue is re-opened to community anyone can pick issue again**

**Comment by PulsaraSandeepa** [comment]
May I work on this?

**Comment by YohanKulasinghe** [comment]
Ok sure, Please Proceed
