### ISSUE TITLE
Page Footer component implementation 

### ISSUE THREAD

**Issue by ChanakaUOMIT** [INTECS-ITFAC/intecs_webapp_front-end#32]

**Comment by YohanKulasinghe** [comment]
Footer area contains two main sections 
1. About Us- Which contain vision and mission. [Image_1](https://drive.google.com/file/d/1wTWL66HwHk-vuenXJE5YvcwonuQzr35S/view?usp=sharing)
2. Contact Us - which contact contact details. [Imagr_2](https://drive.google.com/file/d/1HGIblAQeWa9SBk8UZaFtY3TPvT38O_Vz/view?usp=sharing)

Color code should match with images.
Social Icons needs to place according to image provided
User should able to toggle between "Contact Us" and "About Us" sections as they desire.
You can find required resources [Here](https://drive.google.com/drive/folders/1exOa-R8858_MN9a60EMJVmLGjj8zBEW4?usp=sharing)

Contact INTECS Open Source community for any information. (You can find a link to join community in read me file.)

**Comment by rexzing** [comment]
1. About Us
![Footer_1](https://user-images.githubusercontent.com/25826165/79750614-e1e77c80-832e-11ea-8a46-31f5c51675aa.PNG)

2. Contact Us
![Footer_2](https://user-images.githubusercontent.com/25826165/79750654-ee6bd500-832e-11ea-84b8-6e90b020ec89.PNG)

**Comment by SahanAmarsha** [comment]
I would like to work on the '**Footer Component'** of this project.

**Comment by YohanKulasinghe** [comment]
OK, Please Proceed
