### ISSUE TITLE
Enhancement of contributor's profile card

### ISSUE THREAD

**Issue by kelumsampath** [INTECS-ITFAC/intecs_webapp_front-end#41]
Up to now contributor's profile card implemented with basic elements.

Need to implement with follow features:
1. enhance the responsiveness of the contributor's profile card (zoom-in/zoom-out)
2. Reduce profile card width (5 cards per Row)
3. Profile picture, user name, contribution count should appear on card

card view need to be like [this](https://drive.google.com/open?id=1qywBn9oA5s4c-jXpElsYEXxi3hhXdpAp)

**Comment by JayaShakthi97** [comment]
May I try?

**Comment by kelumsampath** [comment]
OK, Please Proceed
