### ISSUE TITLE
Integrating Chat feature with INTECS web site

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#45]

**Comment by YohanKulasinghe** [comment]
- User will see icon for chat in bottom right  Conner 
- Whenever user visits to site , a default message should visible as follows  "Hi, We are here to answer any questions you have"
- By clicking that user able to send message to INTECS Facebook page.
- UI for the feature is as [follows](https://drive.google.com/file/d/1DuIN6IsjhXht8bCO4mPStg2aN-vIx5jj/view?usp=sharing)

**Comment by piumalns** [comment]
I would like to try this. May I?

**Comment by YohanKulasinghe** [comment]
OK Sure, Please proceed
