### ISSUE TITLE
Add heading banner image with captions  - Event Page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#47]

**Comment by YohanKulasinghe** [comment]
- Head banner of event page 
- It should allow to add some caption on the banner like in the [image](https://drive.google.com/file/d/1f6cVoMRCR3V1FerOZuL5mMXeWlEAb17J/view?usp=sharing) 
- You will find the resources [here](https://drive.google.com/drive/folders/1OTR0aP9HQXYoHXqFp5iAva0Mn3BTx9aa?usp=sharing)

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by PulsaraSandeepa** [comment]
I would like to try this, May I?

**Comment by YohanKulasinghe** [comment]
OK Sure, Please Proceed
