### ISSUE TITLE
Add Left side bar components - Event page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#48]

**Comment by YohanKulasinghe** [comment]
- Left side bar should allow add component as in this [Image](https://drive.google.com/file/d/1cIAISZmvkleQXr6D-FuyiFpixt0vEpFe/view?usp=sharing)
- Use color and styles appropriately 
- Content of side bar should be hard coded for now 

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by SahanAmarsha** [comment]
I can implement the Left Sidebar, may I?

**Comment by kelumsampath** [comment]
sure, please proceed
