### ISSUE TITLE
Add right side bar components - Event Page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#49]

**Comment by YohanKulasinghe** [comment]
- Right side bar should allow add component as in this [Image](https://drive.google.com/file/d/1sfe_YLUkcQKCGos9X7J775dtcUET2yLU/view?usp=sharing)
- Use color and styles appropriately
- Content of side bar should be hard coded for now

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by NimperX** [comment]
I would like to proceed with this issue
