### ISSUE TITLE
Add Pagination UI - Event Page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#50]

**Comment by YohanKulasinghe** [comment]
- Pagination should allow to load event article in future 
- This task is for implementing UI for pagination
- Following image will guide you the place of implementation [click here](https://drive.google.com/file/d/1nq7mG6rJYqXX4-aJWPe5z8Mczi9K81Ko/view?usp=sharing)
- Use styles as desire (for now)

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by NimperX** [comment]
I'll continue with this enhancement

**Comment by YohanKulasinghe** [comment]
OK Sure, Please Proceed
