### ISSUE TITLE
CI/CD configuration

### ISSUE THREAD

**Issue by kelumsampath** [INTECS-ITFAC/intecs_webapp_front-end#55]
following features need to be implemented:
1. each pull request for dev branch should build and deploy (free hosting service)
2. each merge in staging and master branch should deploy (same above)
3. highly need to concern about security (eg: - configuration data [passwords/token/username] need to store in secrets (encrypted)

**Comment by BhanukaUOM** [comment]
I will continue working on this.

**Comment by kelumsampath** [comment]
ok, please proceed
