### ISSUE TITLE
In footer, Social Icons are not comply with zoom in and zoom out

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#61]

**Comment by YohanKulasinghe** [comment]
- Responsiveness issue in social icons 
- You can recreate issue by zoom in and zoom out 
- Here is the issue [click Here](https://drive.google.com/file/d/1eSkoNs0NQjXpnE9i7CbHBYAUQizY1qKZ/view?usp=sharing)
Tip
- To fix this issue you have to rearrange responsive of footer component 

Contact INTECS Open Source community for more information. (You can find a link to join community in read me file.)

**Comment by SahanAmarsha** [comment]
I have fixed it ayiye.

**Comment by YohanKulasinghe** [comment]
Great, Did you put PR
