### ISSUE TITLE
Navbar Tabs and Navigation links needs to upgrade

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#62]

**Comment by YohanKulasinghe** [comment]
- Navbar links should set as follows 

Home
Events
Project
...LinkIT
...INTECS OpenSource
...Student's Work
Gallery

- In project Tab following are sub-menus "LinkIT, INTECS Open Source, Student Works" 
- Each Submenu Item should navigate to a different page.
(Observe Event and home)

Contact INTECS Open Source community for more information. (You can find a link to join the community in read me file.)

**Comment by Tashimadilrukshi** [comment]
May I try this?

**Comment by YohanKulasinghe** [comment]
OK Sure, You can proceed
