### ISSUE TITLE
Navbar Styling 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#63]

**Comment by YohanKulasinghe** [comment]
- Styling of navbar should look like this [Click Here](https://drive.google.com/file/d/1Ql5r5iEn6nE09FNzFRWesE4x5x2Yov1t/view?usp=sharing)
- You have the freedom to adjust height, transparency levels as desire.

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by JayaShakthi97** [comment]
May I try this?

**Comment by YohanKulasinghe** [comment]
Ok Sure, Please Proceed

**Comment by JayaShakthi97** [comment]
Should I work more on this?

**Comment by YohanKulasinghe** [comment]
Yes please, Since the issue is not closed you can add more convenient styles. Especially on submenus. Contact @ChanakaUOMIT to get to know why the issue still didn't close.

**Comment by JayaShakthi97** [comment]
Ok sure.
