### ISSUE TITLE
Alignment Issue in Event Flow Section

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#64]

**Comment by YohanKulasinghe** [comment]
- In component when day shows on the left side, related content shows on the right side, If day shows in the right side, related content shows on the left side. 
- Issue is, one component content overlaps with another component day 
- [Click Here](https://drive.google.com/file/d/1LUKL0cIfU9ylef3O1SBMKb6mnrlsE7rJ/view?usp=sharing)
- Fix for appropriate way.

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by Tashimadilrukshi** [comment]
May I fix this?
