### ISSUE TITLE
Event Flow and Latest Event got overlapped 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#72]

**Comment by YohanKulasinghe** [comment]
- [Click here ](https://drive.google.com/file/d/10uNdfT2k89Jgqh_rpMze4Tk1gDMsWOQF/view?usp=sharing) to view bug 
- Latest event should be on top and event flow should be in below that 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by Tashimadilrukshi** [comment]
I fixed this issue.
