### ISSUE TITLE
LinkIT Page - Implementing Header Section for linkIT page

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#78]

**Comment by YohanKulasinghe** [comment]
In Navbar under the project, you will find a sub-menu item call LinkIT, That is there to collect articles from student and publish it under linkIT program
- Header component for that page should look like this [Click Here](https://drive.google.com/file/d/1fE42YXuhJmCSp4AQa-i9wzWdeQwIGnlQ/view?usp=sharing)
- There you need to add a button to connect following google form ( Please refer the above image)

Google form link: https://forms.gle/xFpE5kX1Zj3fHReo6

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by NimperX** [comment]
May I work on this enhancement

**Comment by YohanKulasinghe** [comment]
OK Sure, You can proceed
