### ISSUE TITLE
Re Locate About Us section

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#79]

**Comment by YohanKulasinghe** [comment]
- Currently About Us is in footer section. 
- Recent discussion, the committee decided to relocate about us section to new navbar tab 
- Task 01 : Remove current about us section
- Task 02 :  Add new tab to navbar after the "gallery" tab stating "About Us"
(Content of about us is not addressed in this issue, here only consider the relocating)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by JayaShakthi97** [comment]
May I work on this?

**Comment by YohanKulasinghe** [comment]
OK Sure, Please Proceed
