### ISSUE TITLE
LinkIT Page - Implementing Posts Grid 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#80]

**Comment by YohanKulasinghe** [comment]
- Under the header section (Refer issue no #78) following grid needs to implement 
- [Click here ](https://drive.google.com/file/d/1ys_fxoFFJ0A7lg_icntDBYZM23F73f31/view?usp=sharing)

- Please take a look at the following FB post. to get an idea on which kind of post will publish in this section 
Facebook Post : https://web.facebook.com/intecs.lk/photos/a.10155766106915257/10163340403715257/?type=3&eid=ARCgTAXt7lwdyPlf8HK5S3LSXGF3rXZcbj7mG437G3UR7E7SGX_TvKPENPtAUSEH1ckz8GUCxQbjb8L8&__tn__=EHH-R

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by SahanAmarsha** [comment]
May I implement this?

**Comment by YohanKulasinghe** [comment]
OK Sure, Please Proceed
