### ISSUE TITLE
INTECS opensource projects Page - Implementing the header section

### ISSUE THREAD

**Issue by csranasinghe** [INTECS-ITFAC/intecs_webapp_front-end#84]
This is the page which showcase our ongoing opensource projects and their details. You can check current status of this page using [this link](https://intecs-dev.web.app/INTECSOpenSourceProjects). In this issue you need to focus on the header section of the page.

- Header should be like this 
![header](https://user-images.githubusercontent.com/25826165/81220384-d9659600-8ffe-11ea-804a-17fa01c9f3f1.png)
- You can take following photo as your background image  
[link to background image](https://unsplash.com/photos/xrVDYZRGdw4)
- Color code used in heart icon: #cc2e72

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by JayaShakthi97** [comment]
I can work on this

**Comment by csranasinghe** [comment]
Cool.. You can proceed.
