### ISSUE TITLE
INTECS opensource projects Page - Implementing page contents section

### ISSUE THREAD

**Issue by csranasinghe** [INTECS-ITFAC/intecs_webapp_front-end#85]
This is the page which showcase our ongoing opensource projects and their details. You can check current status of this page using [this link](https://intecs-dev.web.app/INTECSOpenSourceProjects). In this issue you need to focus on the page contents of the page. Page content goes right after the page header.(refer issue #84 ). In this issue you may have to create two types of components as follows
- Left image component
![bosy left image](https://user-images.githubusercontent.com/25826165/81221469-81c82a00-9000-11ea-9429-140b7bd4e68c.png)
- Right image component
![image-right](https://user-images.githubusercontent.com/25826165/81221575-a8866080-9000-11ea-8edf-324587688097.png)

- Overall page should be like this
![FULLPAGE](https://user-images.githubusercontent.com/25826165/81221631-ba680380-9000-11ea-91b9-4612694f57f0.png)

- Color code used : #cc2e72
- Use freely available images and dummy texts for project contents

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by Tashimadilrukshi** [comment]
May I try this?

**Comment by csranasinghe** [comment]
Sure. Pls go ahead.
