### ISSUE TITLE
INTECS students work page - Implementing the header section

### ISSUE THREAD

**Issue by csranasinghe** [INTECS-ITFAC/intecs_webapp_front-end#86]
This is the page which showcase the student's projects and their details. You can check current status of this page using [this link](https://intecs-dev.web.app/studentsWork). In this issue you need to focus on the header section of the page.

- Header should be like this 
![header](https://user-images.githubusercontent.com/25826165/81285340-0062ad00-907d-11ea-985f-fc0286a210d8.png)
- You can take following photo as your background image  
[link to background image](https://unsplash.com/photos/SYTO3xs06fU)
- Color code used in submit button: #4054b2
- background image overlay: 
[link to background image overlay](https://www.tyler.com/wp-content/uploads/2017/11/brushed-alum.png)

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by asekawa** [comment]
i will give a try on this

**Comment by csranasinghe** [comment]
Nice.. you can start working on this. Contact us If you need any clarifications
