### ISSUE TITLE
Implementing Admin Portal - Sign In page UI

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#92]

**Comment by YohanKulasinghe** [comment]
- Sign In page locate in  "https://intecs-dev.web.app/login"
- Currently, auth guard services are not protected route address 

Task, 
- Design sign-in page and page background as follows
![Picture1](https://user-images.githubusercontent.com/28680211/81465249-4b4c0400-91e6-11ea-862a-28ec13f39435.jpg)

- Remove top navbar 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by SahanAmarsha** [comment]
I can implement this

**Comment by YohanKulasinghe** [comment]
OK, You can proceed
