### ISSUE TITLE
Implementing Admin Dashboard navbar 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#93]

**Comment by YohanKulasinghe** [comment]
- Dashboard locate in "https://intecs-dev.web.app/dashboard"
- The existing navbar needs to remove.
- Need to add a new navbar relevant to the admin dashboard.
![nav](https://user-images.githubusercontent.com/28680211/81466630-c2869580-91f0-11ea-8dcb-f16ef8144cce.PNG)
- Need to compatible with sidebar 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by I3han** [comment]
I'll do it

**Comment by I3han** [comment]
I can do it

**Comment by YohanKulasinghe** [comment]
OK, Please Proceed
