### ISSUE TITLE
Implementing Admin Dashboard sidebar navigation 

### ISSUE THREAD

**Issue by YohanKulasinghe** [INTECS-ITFAC/intecs_webapp_front-end#94]

**Comment by YohanKulasinghe** [comment]
- Needs to implement  side navbar 
- By clicking an item in the sidebar should navigate to following areas 

![sidebar](https://user-images.githubusercontent.com/28680211/81466721-66704100-91f1-11ea-9d8e-4092a4a6fdcb.PNG)


  - Event Management
  - Flow Management
  - News Management 
  - LinkIT
  - Add student work 
  - Open Source Management 

Contact INTECS Open Source community for more information. (You can find a link to join the community in Read me file.)

**Comment by JayaShakthi97** [comment]
I like to work on this

**Comment by YohanKulasinghe** [comment]
Ok, You can proceed
